import { describe, expect, it } from 'vitest'
import { commitMessageViolations } from '../commit-message.ts'

const IDENTITY = 'someone@example.com'

const CLEAN = [
  'set up toolchain and ci',
  '',
  'One command runs every repository check: pnpm verify.',
  'Convention checks land before there is any code to violate them.',
  'No application code yet.',
].join('\n')

function reasons(message: string, identity = IDENTITY): string[] {
  return commitMessageViolations(message, identity).map((violation) => violation.reason)
}

describe('commitMessageViolations', () => {
  it('accepts a subject, a body and nothing else', () => {
    expect(commitMessageViolations(CLEAN, IDENTITY)).toEqual([])
  })

  it('accepts a bare subject line', () => {
    expect(commitMessageViolations('set up toolchain and ci', IDENTITY)).toEqual([])
  })

  describe('attribution trailers', () => {
    it.each([
      'Co-Authored-By: Someone <someone@example.com>',
      'Co-authored-by: An Agent <noreply@anthropic.com>',
      'Reviewed-by: Another Agent <noreply@moonshot.cn>',
      'Authored-By: Whoever <whoever@example.com>',
    ])('rejects %s', (trailer) => {
      expect(reasons(`subject line\n\n${trailer}`)).toContain('attribution trailer')
    })

    it('rejects an agent address from a vendor nobody listed', () => {
      const message = 'subject line\n\nCo-Authored-By: Some Model <noreply@example-vendor.test>'
      expect(reasons(message)).toContain('attribution trailer')
    })

    it('allows Signed-off-by carrying the commit author', () => {
      const message = `subject line\n\nSigned-off-by: A Human <${IDENTITY}>`
      expect(commitMessageViolations(message, IDENTITY)).toEqual([])
    })

    it('rejects Signed-off-by carrying anybody who is not the author', () => {
      const message = 'subject line\n\nSigned-off-by: Someone Else <other@example.com>'
      expect(reasons(message)).toContain('attribution trailer')
    })

    // The addresses differ only in that one contains the other, so a
    // containment test written without the angle brackets would call them
    // equal. A pair differing at the first character establishes nothing here.
    it('rejects a sign-off whose address merely contains the author address', () => {
      const message = 'subject line\n\nSigned-off-by: B <ba@example.test>'
      expect(reasons(message, 'a@example.test')).toContain('attribution trailer')
    })

    it('rejects Signed-off-by when the author address is unknown', () => {
      const message = `subject line\n\nSigned-off-by: A Human <${IDENTITY}>`
      expect(reasons(message, '')).toContain('attribution trailer')
    })
  })

  describe('session trailers and URLs', () => {
    it.each(['Claude-Session: abc123', 'Some-Session: xyz'])('rejects %s', (trailer) => {
      expect(reasons(`subject line\n\n${trailer}`)).toContain('session trailer')
    })

    it.each([
      'https://claude.ai/session/abc-123',
      'https://example.test/traces/9',
      'https://example.test/conversation/9',
      'https://example.test/chat/9',
    ])('rejects the body URL %s', (url) => {
      expect(reasons(`subject line\n\nsee ${url} for context`)).toContain(
        'session, trace or conversation URL',
      )
    })

    it('leaves an ordinary URL alone', () => {
      const message = 'subject line\n\nsee https://www.gnu.org/licenses/agpl-3.0.txt'
      expect(commitMessageViolations(message, IDENTITY)).toEqual([])
    })
  })

  describe('generated-by lines', () => {
    it.each([
      'Generated with a tool',
      'generated by a tool',
      'Assisted by a tool',
      'Written by a tool',
    ])('rejects %s', (phrase) => {
      expect(reasons(`subject line\n\n${phrase}`)).toContain('generated-by line')
    })
  })

  describe('emoji', () => {
    it('rejects an emoji in the subject', () => {
      expect(reasons('set up toolchain ✨')).toContain('emoji')
    })

    it('rejects an emoji in the body', () => {
      expect(reasons('subject line\n\nall done 🎉')).toContain('emoji')
    })

    it('rejects a flag built from regional indicators', () => {
      expect(reasons('subject line\n\n🇬🇧')).toContain('emoji')
    })
  })

  describe('the trailer block', () => {
    it('rejects a trailer that is not on the allow list', () => {
      expect(reasons('subject line\n\nRefs: PROJ-1')).toContain(
        'trailer "Refs" is not on the allow list',
      )
    })

    it('does not treat a one-line subject containing a colon as a trailer', () => {
      expect(commitMessageViolations('fix: a thing', IDENTITY)).toEqual([])
    })

    it('does not treat a prose final paragraph as a trailer block', () => {
      const message = 'subject line\n\nNote: the body may contain a colon.\nSo may this line.'
      expect(commitMessageViolations(message, IDENTITY)).toEqual([])
    })

    it('reports the line number of the offending trailer', () => {
      const message = 'subject line\n\nbody\n\nCo-Authored-By: Agent <noreply@example.test>'
      expect(commitMessageViolations(message, IDENTITY)).toEqual([
        {
          line: 5,
          text: 'Co-Authored-By: Agent <noreply@example.test>',
          reason: 'attribution trailer',
        },
      ])
    })
  })
})
